# Generated by Django 4.2.17 on 2024-12-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, default='Удалённый пользователь', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(blank=True, default='Удалённый пользователь', max_length=100),
        ),
    ]
