# Generated by Django 4.2.17 on 2024-12-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_author_name_post_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
    ]
